# playground is a simple testbed
apiVersion: v1
kind: List
items:

# service definition
- apiVersion: v1
  kind: Service
  metadata:
    name: playground
    labels:
      app: playground
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/scheme: "http"
      prometheus.io/port: "8080"
  spec:
    ports:
    - port: 80
      targetPort: 9090
    selector:
      app: playground

# Default route for git service
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: playground
    name: playground
  spec:
    to:
      name: playground

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: playground
    labels:
      app: playground
  spec:
    strategy:
      type: Recreate
    replicas: 1
    selector:
      app: playground
    template:
      metadata:
        labels:
          app: playground
      spec:
        containers:
        - name: playground
          image: mchudgins/playground:latest
          args:
            - hello
            - --port
            - :9090
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          ports:
          - containerPort: 8080
            protocol: TCP
          restartPolicy: Never

